[project]
name = "tetracorder-lite"
version = "1.1.0"
description = "Containerized USGS Tetracorder (v6) for EMIT mineral identification"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "tetrapy[docs]",
]

[tool.uv.sources]
tetrapy = { git="https://github.com/jammont/tetrapy", branch="main" }
